// 50+ Real Recipes with Lifestyle Variants and Real Images from Unsplash
export const BASE_RECIPES = [
  // BREAKFAST (7)
  { id: "scrambled-eggs", name: "Fluffy Scrambled Eggs", imageUrl: "https://images.unsplash.com/photo-1585525046569-b62a0c65b4a4?w=500&h=400&fit=crop", timeTag: "10 min", methods: ["skillet", "stove"], focus: ["no-restrictions", "keto", "paleo"], variants: ["Classic", "Cheese-Loaded", "Veggie Mix"], spiceLevel: "mild" },
  { id: "greek-yogurt-bowl", name: "Greek Yogurt Protein Bowl", imageUrl: "https://images.unsplash.com/photo-1590080876351-cd381c67b404?w=500&h=400&fit=crop", timeTag: "5 min", methods: ["no-cook"], focus: ["no-restrictions", "keto"], variants: ["Higher Protein", "Low Sugar", "Granola-Topped"], spiceLevel: "none" },
  { id: "oatmeal-berries", name: "Overnight Oats & Berries", imageUrl: "https://images.unsplash.com/photo-1590301845551-faf91d16b84d?w=500&h=400&fit=crop", timeTag: "5 min", methods: ["no-cook"], focus: ["no-restrictions"], variants: ["Budget-Friendly", "Protein-Packed", "Chocolate-Almond"], spiceLevel: "none" },
  { id: "pancakes", name: "Fluffy Protein Pancakes", imageUrl: "https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=500&h=400&fit=crop", timeTag: "15 min", methods: ["skillet", "stove"], focus: ["no-restrictions"], variants: ["Banana-Split", "Blueberry", "Low-Carb"], spiceLevel: "mild" },
  { id: "breakfast-burrito", name: "Breakfast Burrito", imageUrl: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=500&h=400&fit=crop", timeTag: "20 min", methods: ["skillet", "stove"], focus: ["no-restrictions"], variants: ["Meat-Lovers", "Veggie", "Budget-Friendly"], spiceLevel: "medium" },
  { id: "smoothie-bowl", name: "Acai Smoothie Bowl", imageUrl: "https://images.unsplash.com/photo-1590080876351-cd381c67b404?w=500&h=400&fit=crop", timeTag: "8 min", methods: ["blender", "no-cook"], focus: ["no-restrictions"], variants: ["Tropical", "Berry", "Protein-Boost"], spiceLevel: "none" },
  { id: "egg-muffins", name: "Meal-Prep Egg Muffins", imageUrl: "https://images.unsplash.com/photo-1585521537967-87a58f6aa8c2?w=500&h=400&fit=crop", timeTag: "25 min", methods: ["oven"], focus: ["no-restrictions", "keto"], variants: ["Veggie", "Meat & Cheese", "Keto-Max"], spiceLevel: "mild" },

  // LUNCH (10)
  { id: "grilled-chicken-salad", name: "Grilled Chicken Salad", imageUrl: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=500&h=400&fit=crop", timeTag: "20 min", methods: ["grill", "skillet"], focus: ["no-restrictions", "paleo"], variants: ["Caesar", "Asian", "Mediterranean"], spiceLevel: "mild" },
  { id: "tuna-sandwich", name: "Classic Tuna Sandwich", imageUrl: "https://images.unsplash.com/photo-1541519227354-08fa5d50c44d?w=500&h=400&fit=crop", timeTag: "10 min", methods: ["no-cook"], focus: ["no-restrictions"], variants: ["Whole-Wheat", "Low-Calorie Mayo", "Veggie-Loaded"], spiceLevel: "mild" },
  { id: "turkey-wrap", name: "Turkey & Avocado Wrap", imageUrl: "https://images.unsplash.com/photo-1571115177098-24ec42ed204d?w=500&h=400&fit=crop", timeTag: "8 min", methods: ["no-cook"], focus: ["no-restrictions", "paleo"], variants: ["Spicy", "Classic", "Veggie-Only"], spiceLevel: "medium" },
  { id: "quinoa-bowl", name: "Rainbow Quinoa Bowl", imageUrl: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=500&h=400&fit=crop", timeTag: "20 min", methods: ["pot", "stovetop"], focus: ["no-restrictions"], variants: ["Buddha-Style", "Asian", "Mediterranean"], spiceLevel: "mild" },
  { id: "pulled-pork-sandwich", name: "Slow-Cooker Pulled Pork", imageUrl: "https://images.unsplash.com/photo-1555939594-58d7cb561241?w=500&h=400&fit=crop", timeTag: "8 hrs", methods: ["slow-cooker"], focus: ["no-restrictions", "keto"], variants: ["Smoky", "Spicy", "Carolina-Style"], spiceLevel: "medium" },
  { id: "salmon-rice-bowl", name: "Baked Salmon & Rice", imageUrl: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=500&h=400&fit=crop", timeTag: "25 min", methods: ["oven", "stovetop"], focus: ["no-restrictions", "paleo"], variants: ["Dill-Lemon", "Teriyaki", "Garlic-Butter"], spiceLevel: "mild" },
  { id: "beef-tacos", name: "Ground Beef Tacos", imageUrl: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=500&h=400&fit=crop", timeTag: "15 min", methods: ["skillet", "stove"], focus: ["no-restrictions"], variants: ["Spicy", "Budget-Friendly", "Cauliflower-Crust"], spiceLevel: "medium" },
  { id: "caprese-salad", name: "Caprese Salad", imageUrl: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=500&h=400&fit=crop", timeTag: "10 min", methods: ["no-cook"], focus: ["no-restrictions"], variants: ["Classic", "Balsamic-Glaze", "Arugula"], spiceLevel: "mild" },
  { id: "chickpea-salad", name: "Mediterranean Chickpea Salad", imageUrl: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=500&h=400&fit=crop", timeTag: "15 min", methods: ["no-cook"], focus: ["no-restrictions"], variants: ["Herb-Forward", "Lemon-Heavy", "Spiced"], spiceLevel: "mild" },
  { id: "tuna-poke-bowl", name: "Tuna Poke Bowl", imageUrl: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=500&h=400&fit=crop", timeTag: "15 min", methods: ["no-cook"], focus: ["no-restrictions"], variants: ["Spicy", "Sesame", "Classic"], spiceLevel: "medium" },

  // DINNER (12)
  { id: "sheet-pan-chicken", name: "Sheet-Pan Chicken & Veg", imageUrl: "https://images.unsplash.com/photo-1598103442097-8b74394b95c6?w=500&h=400&fit=crop", timeTag: "40 min", methods: ["oven", "sheet pan"], focus: ["no-restrictions", "keto", "paleo"], variants: ["Italian", "Mediterranean", "Spicy"], spiceLevel: "mild" },
  { id: "beef-chili", name: "Hearty Beef Chili", imageUrl: "https://images.unsplash.com/photo-1599599810694-b5ac4dd64b73?w=500&h=400&fit=crop", timeTag: "60 min", methods: ["pot", "stovetop"], focus: ["no-restrictions", "keto"], variants: ["Extra-Spicy", "Low-Carb", "Meat-Lovers"], spiceLevel: "hot" },
  { id: "shrimp-stir-fry", name: "Quick Shrimp Stir-Fry", imageUrl: "https://images.unsplash.com/photo-1609501676725-7186f017a4b0?w=500&h=400&fit=crop", timeTag: "20 min", methods: ["wok", "skillet"], focus: ["no-restrictions", "keto"], variants: ["Spicy", "Garlic-Heavy", "Low-Sodium"], spiceLevel: "hot" },
  { id: "spaghetti-bolognese", name: "Spaghetti Bolognese", imageUrl: "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=500&h=400&fit=crop", timeTag: "35 min", methods: ["pot", "stovetop"], focus: ["no-restrictions"], variants: ["Low-Carb", "Extra-Veggie", "Lean-Meat"], spiceLevel: "mild" },
  { id: "grilled-steak", name: "Grass-Fed Grilled Steak", imageUrl: "https://images.unsplash.com/photo-1432139555190-58524dae6a55?w=500&h=400&fit=crop", timeTag: "20 min", methods: ["grill", "skillet"], focus: ["no-restrictions", "keto", "paleo"], variants: ["Ribeye", "NY-Strip", "Filet-Mignon"], spiceLevel: "mild" },
  { id: "baked-salmon", name: "Herb-Baked Salmon", imageUrl: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=500&h=400&fit=crop", timeTag: "25 min", methods: ["oven"], focus: ["no-restrictions", "paleo"], variants: ["Dill", "Lemon-Pepper", "Teriyaki"], spiceLevel: "mild" },
  { id: "chicken-curry", name: "Thai Chicken Curry", imageUrl: "https://images.unsplash.com/photo-1588166524941-3bf61d4fa3e3?w=500&h=400&fit=crop", timeTag: "30 min", methods: ["pot", "stovetop"], focus: ["no-restrictions"], variants: ["Red-Curry", "Green-Curry", "Coconut-Mild"], spiceLevel: "hot" },
  { id: "turkey-meatballs", name: "Baked Turkey Meatballs", imageUrl: "https://images.unsplash.com/photo-1598308737221-69b9ae33f95c?w=500&h=400&fit=crop", timeTag: "30 min", methods: ["oven"], focus: ["no-restrictions"], variants: ["Swedish", "Italian", "Asian"], spiceLevel: "mild" },
  { id: "cauliflower-rice", name: "Cauliflower Fried Rice", imageUrl: "https://images.unsplash.com/photo-1571115177098-24ec42ed204d?w=500&h=400&fit=crop", timeTag: "20 min", methods: ["wok", "skillet"], focus: ["keto", "paleo"], variants: ["Spicy", "Egg-Fried", "Vegetarian"], spiceLevel: "medium" },
  { id: "fish-tacos", name: "Crispy Fish Tacos", imageUrl: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=500&h=400&fit=crop", timeTag: "25 min", methods: ["skillet"], focus: ["no-restrictions"], variants: ["Spicy-Lime", "Classic", "Grilled"], spiceLevel: "medium" },
  { id: "shrimp-scampi", name: "Garlic Shrimp Scampi", imageUrl: "https://images.unsplash.com/photo-1609501676725-7186f017a4b0?w=500&h=400&fit=crop", timeTag: "20 min", methods: ["skillet"], focus: ["no-restrictions", "keto"], variants: ["White-Wine", "Butter-Garlic", "Spicy"], spiceLevel: "medium" },
  { id: "lamb-meatballs", name: "Mediterranean Lamb Meatballs", imageUrl: "https://images.unsplash.com/photo-1598308737221-69b9ae33f95c?w=500&h=400&fit=crop", timeTag: "30 min", methods: ["oven"], focus: ["no-restrictions"], variants: ["Yogurt-Sauce", "Tomato-Based", "Spiced"], spiceLevel: "medium" },

  // SOUPS & SIDES (7)
  { id: "chicken-soup", name: "Classic Chicken Soup", imageUrl: "https://images.unsplash.com/photo-1547592166-7aae4d755744?w=500&h=400&fit=crop", timeTag: "45 min", methods: ["pot", "stovetop"], focus: ["no-restrictions", "paleo"], variants: ["Extra-Veggie", "Bone-Broth", "Asian"], spiceLevel: "mild" },
  { id: "lentil-soup", name: "Hearty Lentil Soup", imageUrl: "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=500&h=400&fit=crop", timeTag: "40 min", methods: ["pot", "stovetop"], focus: ["no-restrictions"], variants: ["Spiced", "Creamy", "Extra-Protein"], spiceLevel: "medium" },
  { id: "minestrone", name: "Italian Minestrone", imageUrl: "https://images.unsplash.com/photo-1612621776292-7ac56d7f7f1e?w=500&h=400&fit=crop", timeTag: "35 min", methods: ["pot", "stovetop"], focus: ["no-restrictions"], variants: ["Vegetarian", "Meat-Added", "Pasta-Free"], spiceLevel: "mild" },
  { id: "roasted-veggies", name: "Roasted Root Vegetables", imageUrl: "https://images.unsplash.com/photo-1599599810694-b5ac4dd64b73?w=500&h=400&fit=crop", timeTag: "30 min", methods: ["oven"], focus: ["no-restrictions"], variants: ["Garlic-Herb", "Balsamic", "Spicy-Paprika"], spiceLevel: "mild" },
  { id: "asparagus-bacon", name: "Asparagus with Bacon", imageUrl: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=500&h=400&fit=crop", timeTag: "20 min", methods: ["oven"], focus: ["no-restrictions", "keto", "paleo"], variants: ["Parmesan", "Garlic", "Plain"], spiceLevel: "mild" },
  { id: "broccoli-cheddar", name: "Roasted Broccoli & Cheddar", imageUrl: "https://images.unsplash.com/photo-1599599810694-b5ac4dd64b73?w=500&h=400&fit=crop", timeTag: "25 min", methods: ["oven"], focus: ["no-restrictions", "keto"], variants: ["Extra-Cheese", "Light-Cheese", "Garlic"], spiceLevel: "mild" },
  { id: "sweet-potato-fries", name: "Air-Fryer Sweet Potato Fries", imageUrl: "https://images.unsplash.com/photo-1585521537967-87a58f6aa8c2?w=500&h=400&fit=crop", timeTag: "20 min", methods: ["air-fryer"], focus: ["no-restrictions"], variants: ["Spiced", "Cilantro-Lime", "Classic"], spiceLevel: "mild" },

  // SNACKS & LIGHT MEALS (6)
  { id: "hummus-platter", name: "Hummus & Veggie Platter", imageUrl: "https://images.unsplash.com/photo-1599599810694-b5ac4dd64b73?w=500&h=400&fit=crop", timeTag: "5 min", methods: ["no-cook"], focus: ["no-restrictions"], variants: ["Garlic", "Roasted-Red-Pepper", "Plain"], spiceLevel: "mild" },
  { id: "cheese-board", name: "Charcuterie Board", imageUrl: "https://images.unsplash.com/photo-1602694742023-93c60c76d2d6?w=500&h=400&fit=crop", timeTag: "10 min", methods: ["no-cook"], focus: ["no-restrictions", "keto"], variants: ["Meat-Heavy", "Cheese-Focus", "Fruit-Included"], spiceLevel: "none" },
  { id: "protein-bars", name: "Homemade Protein Bars", imageUrl: "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=500&h=400&fit=crop", timeTag: "15 min", methods: ["no-cook"], focus: ["no-restrictions"], variants: ["Peanut-Butter", "Chocolate", "Almond"], spiceLevel: "none" },
  { id: "trail-mix", name: "Custom Trail Mix", imageUrl: "https://images.unsplash.com/photo-1585621826411-b3b9fce44e6b?w=500&h=400&fit=crop", timeTag: "5 min", methods: ["no-cook"], focus: ["no-restrictions"], variants: ["Nuts-Only", "Dried-Fruit", "Dark-Chocolate"], spiceLevel: "none" },
  { id: "deviled-eggs", name: "Deviled Eggs", imageUrl: "https://images.unsplash.com/photo-1585525046569-b62a0c65b4a4?w=500&h=400&fit=crop", timeTag: "15 min", methods: ["no-cook"], focus: ["no-restrictions", "keto"], variants: ["Classic", "Spicy", "Herb"], spiceLevel: "mild" },
  { id: "guac-chips", name: "Fresh Guacamole & Chips", imageUrl: "https://images.unsplash.com/photo-1599599810694-b5ac4dd64b73?w=500&h=400&fit=crop", timeTag: "8 min", methods: ["no-cook"], focus: ["no-restrictions"], variants: ["Lime-Heavy", "Cilantro", "Spicy"], spiceLevel: "medium" },

  // VEGETARIAN & VEGAN (8)
  { id: "lentil-dal", name: "Indian Lentil Dal", imageUrl: "https://images.unsplash.com/photo-1547592166-7aae4d755744?w=500&h=400&fit=crop", timeTag: "35 min", methods: ["pot", "stovetop"], focus: ["no-restrictions"], variants: ["Mild", "Spicy", "Coconut-Cream"], spiceLevel: "medium" },
  { id: "chickpea-curry", name: "Chickpea Curry", imageUrl: "https://images.unsplash.com/photo-1588166524941-3bf61d4fa3e3?w=500&h=400&fit=crop", timeTag: "30 min", methods: ["pot", "stovetop"], focus: ["no-restrictions"], variants: ["Red-Sauce", "Coconut", "Dry-Curry"], spiceLevel: "hot" },
  { id: "veggie-stir-fry", name: "Vegetable Stir-Fry", imageUrl: "https://images.unsplash.com/photo-1609501676725-7186f017a4b0?w=500&h=400&fit=crop", timeTag: "20 min", methods: ["wok", "skillet"], focus: ["no-restrictions"], variants: ["Garlic-Ginger", "Spicy", "Cashew"], spiceLevel: "medium" },
  { id: "black-bean-burger", name: "Black Bean Burger", imageUrl: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=500&h=400&fit=crop", timeTag: "25 min", methods: ["skillet"], focus: ["no-restrictions"], variants: ["Spicy", "Cheese-Topped", "Plain"], spiceLevel: "medium" },
  { id: "stuffed-peppers", name: "Stuffed Bell Peppers", imageUrl: "https://images.unsplash.com/photo-1599599810694-b5ac4dd64b73?w=500&h=400&fit=crop", timeTag: "40 min", methods: ["oven"], focus: ["no-restrictions"], variants: ["Meat-Rice", "Quinoa-Vegan", "Cheese-Loaded"], spiceLevel: "mild" },
  { id: "eggplant-parmesan", name: "Eggplant Parmesan", imageUrl: "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=500&h=400&fit=crop", timeTag: "50 min", methods: ["oven"], focus: ["no-restrictions"], variants: ["Classic", "Light-Oil", "Extra-Cheese"], spiceLevel: "mild" },
  { id: "beet-salad", name: "Roasted Beet & Goat Cheese Salad", imageUrl: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=500&h=400&fit=crop", timeTag: "35 min", methods: ["oven"], focus: ["no-restrictions"], variants: ["Walnuts", "Pistachio", "Plain"], spiceLevel: "mild" },
  { id: "mushroom-risotto", name: "Creamy Mushroom Risotto", imageUrl: "https://images.unsplash.com/photo-1599599810694-b5ac4dd64b73?w=500&h=400&fit=crop", timeTag: "30 min", methods: ["pot", "stovetop"], focus: ["no-restrictions"], variants: ["Truffle", "Garlic", "White-Wine"], spiceLevel: "mild" },

  // PASTA & GRAINS (5)
  { id: "baked-ziti", name: "Baked Ziti", imageUrl: "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=500&h=400&fit=crop", timeTag: "35 min", methods: ["oven"], focus: ["no-restrictions"], variants: ["Meat-Sauce", "Vegetarian", "Three-Cheese"], spiceLevel: "mild" },
  { id: "pesto-pasta", name: "Fresh Basil Pesto Pasta", imageUrl: "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=500&h=400&fit=crop", timeTag: "20 min", methods: ["pot", "stovetop"], focus: ["no-restrictions"], variants: ["Classic", "Garlic-Heavy", "Nut-Free"], spiceLevel: "mild" },
  { id: "fried-rice", name: "Vegetable Fried Rice", imageUrl: "https://images.unsplash.com/photo-1571115177098-24ec42ed204d?w=500&h=400&fit=crop", timeTag: "20 min", methods: ["wok", "skillet"], focus: ["no-restrictions"], variants: ["Egg", "Tofu", "Shrimp"], spiceLevel: "medium" },
  { id: "couscous-bowl", name: "Mediterranean Couscous", imageUrl: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=500&h=400&fit=crop", timeTag: "20 min", methods: ["pot", "stovetop"], focus: ["no-restrictions"], variants: ["Vegetarian", "With-Chicken", "Spiced"], spiceLevel: "mild" },
  { id: "pad-thai", name: "Pad Thai Noodles", imageUrl: "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=500&h=400&fit=crop", timeTag: "25 min", methods: ["wok", "skillet"], focus: ["no-restrictions"], variants: ["Shrimp", "Chicken", "Tofu"], spiceLevel: "hot" },

  // SEAFOOD (5)
  { id: "crab-cakes", name: "Pan-Fried Crab Cakes", imageUrl: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=500&h=400&fit=crop", timeTag: "20 min", methods: ["skillet"], focus: ["no-restrictions"], variants: ["Classic", "Cajun", "Lemon-Herb"], spiceLevel: "medium" },
  { id: "baked-cod", name: "Herb-Baked Cod", imageUrl: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=500&h=400&fit=crop", timeTag: "25 min", methods: ["oven"], focus: ["no-restrictions", "paleo"], variants: ["Lemon-Dill", "Tomato-Basil", "Garlic"], spiceLevel: "mild" },
  { id: "seared-scallops", name: "Pan-Seared Scallops", imageUrl: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=500&h=400&fit=crop", timeTag: "15 min", methods: ["skillet"], focus: ["no-restrictions", "keto", "paleo"], variants: ["Garlic-Butter", "Lemon", "Spicy"], spiceLevel: "mild" },
  { id: "mussels-wine", name: "Mussels in White Wine", imageUrl: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=500&h=400&fit=crop", timeTag: "20 min", methods: ["pot", "stovetop"], focus: ["no-restrictions"], variants: ["Classic", "Garlic-Heavy", "Tomato-Based"], spiceLevel: "mild" },
  { id: "grilled-swordfish", name: "Grilled Swordfish Steak", imageUrl: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=500&h=400&fit=crop", timeTag: "15 min", methods: ["grill"], focus: ["no-restrictions", "paleo"], variants: ["Mediterranean", "Spicy", "Garlic"], spiceLevel: "mild" },
];
